# Compliance/Posture — Kubescape scheduled scan
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kubescape-daily
  namespace: security
spec:
  schedule: "15 2 * * *"  # daily 02:15
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: security-tools
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            fsGroup: 65534
          containers:
            - name: kubescape
              image: quay.io/kubescape/kubescape:latest
              securityContext:
                runAsNonRoot: true
                runAsUser: 65534
                readOnlyRootFilesystem: true
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
              args:
                - scan
                - framework
                - nsa,mitre,cis-1.24
                - --format
                - json
                - --output
                - /tmp/kubescape-$(date +%F).json