apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: workers-spot
  namespace: karpenter
spec:
  amiFamily: AL2
  role: karpenter-node-role # IAM role for nodes; ensure it exists or use your own
  subnetSelectorTerms:
    - tags:
        karpenter: "true"
  securityGroupSelectorTerms:
    - tags:
        karpenter: "true"
  tags:
    Name: ${CLUSTER_NAME}-workers-spot